[versions]

androidGradlePlugin = "7.4.2"
kotlin = "1.8.0"

[libraries]

androidx-core = "androidx.core:core-ktx:1.9.0"
androidx-appcompat = "androidx.appcompat:appcompat:1.6.1"

google-android-material = "com.google.android.material:material:1.8.0"

[plugins]

android-app = { id = "com.android.application", version.ref = "androidGradlePlugin" }
android-lib = { id = "com.android.library", version.ref = "androidGradlePlugin" }
android-kotlin = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }

[bundles]